[package]
name = "mining-rust"
version = "0.0.1"
edition = "2021"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
sha2 = "0.10.8"
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
